---
development:
  LINE_CHANNEL_ID: '<LINE_CHANNEL_ID>'
  LINE_CHANNEL_SECRET: '<LINE_CHANNEL_SECRET>'
  LINE_CHANNEL_TOKEN: '<LINE_CHANNEL_TOKEN>'

test:
  LINE_CHANNEL_ID: '<LINE_CHANNEL_ID>'
  LINE_CHANNEL_SECRET: '<LINE_CHANNEL_SECRET>'
  LINE_CHANNEL_TOKEN: '<LINE_CHANNEL_TOKEN>'

production:
  LINE_CHANNEL_ID: '<LINE_CHANNEL_ID>'
  LINE_CHANNEL_SECRET: '<LINE_CHANNEL_SECRET>'
  LINE_CHANNEL_TOKEN: '<LINE_CHANNEL_TOKEN>'
